package com.qhit.lh.g4.wf.t8.bean;
// Generated 2017-12-22 9:37:44 by Hibernate Tools 4.0.1.Final

import com.qhit.lh.g4.wf.t8.bean.Dept;
import com.qhit.lh.g4.wf.t8.bean.Userinfo;

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private int eid;
	private String ename;
	private String esex;
	private String ebirthday;
	private Integer did;


	private Dept dept;
	private Userinfo userinfo;
	
	public Dept getDept() {
		return dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public Userinfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public Emp() {
	}

	public Emp(int eid, String ename, String esex, String ebirthday) {
		this.eid = eid;
		this.ename = ename;
		this.esex = esex;
		this.ebirthday = ebirthday;
	}

	public Emp(int eid, String ename, String esex, String ebirthday, Integer did) {
		this.eid = eid;
		this.ename = ename;
		this.esex = esex;
		this.ebirthday = ebirthday;
		this.did = did;
	}

	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getEsex() {
		return this.esex;
	}

	public void setEsex(String esex) {
		this.esex = esex;
	}

	public String getEbirthday() {
		return this.ebirthday;
	}

	public void setEbirthday(String ebirthday) {
		this.ebirthday = ebirthday;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

}
