package com.qhit.lh.g4.wf.t6.bean;
// Generated 2017-12-20 16:31:43 by Hibernate Tools 5.0.6.Final



/**
 * Userinfo generated by hbm2java
 */
public class Userinfo  implements java.io.Serializable {


     private int uid;
     private String uname;
     private String upwd;
     
     private Emp emp;
     private Role roles;
     
    public Role getRoles() {
		return roles;
	}

	public void setRoles(Role roles) {
		this.roles = roles;
	}

	public Emp getEmp() {
		return emp;
	}

	public void setEmp(Emp emp) {
		this.emp = emp;
	}

	public Userinfo() {
    }

    public Userinfo(int uid, String uname, String upwd) {
       this.uid = uid;
       this.uname = uname;
       this.upwd = upwd;
    }
   
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getUpwd() {
        return this.upwd;
    }
    
    public void setUpwd(String upwd) {
        this.upwd = upwd;
    }




}


