package com.qhit.lh.g4.wf.t3.bean;

import java.util.HashSet;
import java.util.Set;

// Generated 2017-12-15 9:35:55 by Hibernate Tools 5.2.6.Final



/**
 * TDept generated by hbm2java
 */
public class TDept  implements java.io.Serializable {


     private int deptId;
     private String deptName;
     private String adrress;
     
     private Set<TEmp> emps = new HashSet<>();

    public Set<TEmp> getEmps() {
		return emps;
	}

	public void setEmps(Set<TEmp> emps) {
		this.emps = emps;
	}

	public TDept() {
    }

    public TDept(int deptId, String deptName, String adrress) {
       this.deptId = deptId;
       this.deptName = deptName;
       this.adrress = adrress;
    }
   
    public int getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(int deptId) {
        this.deptId = deptId;
    }
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
    public String getAdrress() {
        return this.adrress;
    }
    
    public void setAdrress(String adrress) {
        this.adrress = adrress;
    }




}


