package com.qhit.lh.g4.wf.t3.bean;
// Generated 2017-12-15 9:35:55 by Hibernate Tools 5.2.6.Final



/**
 * TEmp generated by hbm2java
 */
public class TEmp  implements java.io.Serializable {


	private int eid;
	private String empName;
	private String empSex;
	private String brithday;
	private Integer deptId;

	private TUserinfo tuserinfo;
	private TDept tdept;
	public TUserinfo getTuserinfo() {
		return tuserinfo;
	}


	public void setTuserinfo(TUserinfo tuserinfo) {
		this.tuserinfo = tuserinfo;
	}


	public TDept getTdept() {
		return tdept;
	}


	public void setTdept(TDept tdept) {
		this.tdept = tdept;
	}


	public TEmp() {
	}


	public TEmp(int eid, String empName, String empSex, String brithday, Integer deptId) {
		this.eid = eid;
		this.empName = empName;
		this.empSex = empSex;
		this.brithday = brithday;
		this.deptId = deptId;
	}

	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}
	public String getEmpSex() {
		return this.empSex;
	}

	public void setEmpSex(String empSex) {
		this.empSex = empSex;
	}
	public String getBrithday() {
		return this.brithday;
	}

	public void setBrithday(String brithday) {
		this.brithday = brithday;
	}
	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}




}


