package com.qhit.lh.g4.wf.t3.bean;
// Generated 2017-12-15 9:35:55 by Hibernate Tools 5.2.6.Final



/**
 * TUserinfo generated by hbm2java
 */
public class TUserinfo  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String userPwd;
     
     private TEmp temp;

    public TEmp getTemp() {
		return temp;
	}

	public void setTemp(TEmp temp) {
		this.temp = temp;
	}

	public TUserinfo() {
    }

    public TUserinfo(int userId, String userName, String userPwd) {
       this.userId = userId;
       this.userName = userName;
       this.userPwd = userPwd;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPwd() {
        return this.userPwd;
    }
    
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }




}


